#!/usr/bin/env bash
# a script to configure an ubuntu server to have
# 127.0.0.2 as localhost and
# 8.8.8.8 as facebook.com

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
